name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - DOCKERREADME.md
  workflow_dispatch:

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v5
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/z-push
        readme-filepath: DOCKERREADME.md